"""add audit trail: timestamps, soft delete, audit_logs table

Revision ID: 80e4a2510daf
Revises: 0001
Create Date: 2026-08-24 22:43:49.590823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '80e4a2510daf'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('table_name', sa.String(), nullable=False),
    sa.Column('record_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.Enum('insert', 'update', 'delete', name='audit_action_enum'), nullable=False),
    sa.Column('diff', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('changed_by', sa.UUID(), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('daily_logs', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('daily_logs', sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('daily_logs', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('daily_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('uq_daily_logs_gecko_date', 'daily_logs', type_='unique')
    op.create_index('uq_daily_logs_gecko_date_active', 'daily_logs', ['gecko_id', 'date'], unique=True, postgresql_where=sa.text('is_deleted = false'))
    op.add_column('egg_logs', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('egg_logs', sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('egg_logs', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('egg_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.add_column('environment_logs', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('environment_logs', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('environment_logs', sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('environment_logs', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('geckos', sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('geckos', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('geckos', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('geckos', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.add_column('shedding_logs', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('shedding_logs', sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('shedding_logs', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('shedding_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.add_column('shedding_photos', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('shedding_photos', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('shedding_photos', sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('shedding_photos', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('users', sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('users', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.create_index('uq_users_email_active', 'users', ['email'], unique=True, postgresql_where=sa.text('is_deleted = false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_users_email_active', table_name='users', postgresql_where=sa.text('is_deleted = false'))
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('users', 'deleted_at')
    op.drop_column('users', 'is_deleted')
    op.drop_column('users', 'updated_at')
    op.drop_column('shedding_photos', 'deleted_at')
    op.drop_column('shedding_photos', 'is_deleted')
    op.drop_column('shedding_photos', 'updated_at')
    op.drop_column('shedding_photos', 'created_at')
    op.alter_column('shedding_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('shedding_logs', 'deleted_at')
    op.drop_column('shedding_logs', 'is_deleted')
    op.drop_column('shedding_logs', 'updated_at')
    op.alter_column('geckos', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('geckos', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('geckos', 'deleted_at')
    op.drop_column('geckos', 'is_deleted')
    op.drop_column('environment_logs', 'deleted_at')
    op.drop_column('environment_logs', 'is_deleted')
    op.drop_column('environment_logs', 'updated_at')
    op.drop_column('environment_logs', 'created_at')
    op.alter_column('egg_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('egg_logs', 'deleted_at')
    op.drop_column('egg_logs', 'is_deleted')
    op.drop_column('egg_logs', 'updated_at')
    op.drop_index('uq_daily_logs_gecko_date_active', table_name='daily_logs', postgresql_where=sa.text('is_deleted = false'))
    op.create_unique_constraint('uq_daily_logs_gecko_date', 'daily_logs', ['gecko_id', 'date'])
    op.alter_column('daily_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('daily_logs', 'deleted_at')
    op.drop_column('daily_logs', 'is_deleted')
    op.drop_column('daily_logs', 'updated_at')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
