/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/geckos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Geckos */
        get: operations["list_geckos_geckos_get"];
        put?: never;
        /** Create Gecko */
        post: operations["create_gecko_geckos_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/geckos/{gecko_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Gecko */
        get: operations["get_gecko_geckos__gecko_id__get"];
        put?: never;
        post?: never;
        /** Delete Gecko */
        delete: operations["delete_gecko_geckos__gecko_id__delete"];
        options?: never;
        head?: never;
        /** Update Gecko */
        patch: operations["update_gecko_geckos__gecko_id__patch"];
        trace?: never;
    };
    "/geckos/{gecko_id}/photo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Gecko Photo */
        post: operations["upload_gecko_photo_geckos__gecko_id__photo_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/geckos/{gecko_id}/daily-logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Daily Logs */
        get: operations["list_daily_logs_geckos__gecko_id__daily_logs_get"];
        put?: never;
        /** Create Daily Log */
        post: operations["create_daily_log_geckos__gecko_id__daily_logs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/daily-logs/{log_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Daily Log */
        get: operations["get_daily_log_daily_logs__log_id__get"];
        put?: never;
        post?: never;
        /** Delete Daily Log */
        delete: operations["delete_daily_log_daily_logs__log_id__delete"];
        options?: never;
        head?: never;
        /** Update Daily Log */
        patch: operations["update_daily_log_daily_logs__log_id__patch"];
        trace?: never;
    };
    "/geckos/{gecko_id}/shedding-logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Shedding Logs */
        get: operations["list_shedding_logs_geckos__gecko_id__shedding_logs_get"];
        put?: never;
        /** Create Shedding Log */
        post: operations["create_shedding_log_geckos__gecko_id__shedding_logs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/shedding-logs/{log_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Shedding Log */
        get: operations["get_shedding_log_shedding_logs__log_id__get"];
        put?: never;
        post?: never;
        /** Delete Shedding Log */
        delete: operations["delete_shedding_log_shedding_logs__log_id__delete"];
        options?: never;
        head?: never;
        /** Update Shedding Log */
        patch: operations["update_shedding_log_shedding_logs__log_id__patch"];
        trace?: never;
    };
    "/shedding-logs/{log_id}/photos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Shedding Photos */
        post: operations["upload_shedding_photos_shedding_logs__log_id__photos_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/shedding-photos/{photo_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Shedding Photo */
        delete: operations["delete_shedding_photo_shedding_photos__photo_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/geckos/{gecko_id}/environment-logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Environment Logs */
        get: operations["list_environment_logs_geckos__gecko_id__environment_logs_get"];
        put?: never;
        /** Create Environment Log */
        post: operations["create_environment_log_geckos__gecko_id__environment_logs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/environment-logs/{log_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Environment Log */
        get: operations["get_environment_log_environment_logs__log_id__get"];
        put?: never;
        post?: never;
        /** Delete Environment Log */
        delete: operations["delete_environment_log_environment_logs__log_id__delete"];
        options?: never;
        head?: never;
        /** Update Environment Log */
        patch: operations["update_environment_log_environment_logs__log_id__patch"];
        trace?: never;
    };
    "/geckos/{gecko_id}/egg-logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Egg Logs */
        get: operations["list_egg_logs_geckos__gecko_id__egg_logs_get"];
        put?: never;
        /** Create Egg Log */
        post: operations["create_egg_log_geckos__gecko_id__egg_logs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/egg-logs/{log_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Egg Log */
        get: operations["get_egg_log_egg_logs__log_id__get"];
        put?: never;
        post?: never;
        /** Delete Egg Log */
        delete: operations["delete_egg_log_egg_logs__log_id__delete"];
        options?: never;
        head?: never;
        /** Update Egg Log */
        patch: operations["update_egg_log_egg_logs__log_id__patch"];
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_upload_gecko_photo_geckos__gecko_id__photo_post */
        Body_upload_gecko_photo_geckos__gecko_id__photo_post: {
            /**
             * File
             * Format: binary
             */
            file: string;
        };
        /** Body_upload_shedding_photos_shedding_logs__log_id__photos_post */
        Body_upload_shedding_photos_shedding_logs__log_id__photos_post: {
            /** Files */
            files: string[];
        };
        /** DailyLogCreate */
        DailyLogCreate: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /**
             * Status
             * @enum {string}
             */
            status: "fed" | "partial" | "refused" | "skipped";
            /** Qty */
            qty?: number | null;
            /** Food */
            food?: string | null;
            /** Food Size */
            food_size?: string | null;
            /**
             * Poop
             * @default false
             */
            poop: boolean;
            /** Weight */
            weight?: number | null;
            /** Note */
            note?: string | null;
        };
        /** DailyLogRead */
        DailyLogRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Gecko Id
             * Format: uuid
             */
            gecko_id: string;
            /**
             * Date
             * Format: date
             */
            date: string;
            /**
             * Status
             * @enum {string}
             */
            status: "fed" | "partial" | "refused" | "skipped";
            /** Qty */
            qty: number | null;
            /** Food */
            food: string | null;
            /** Food Size */
            food_size: string | null;
            /** Poop */
            poop: boolean;
            /** Weight */
            weight: number | null;
            /** Note */
            note: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** DailyLogUpdate */
        DailyLogUpdate: {
            /** Date */
            date?: string | null;
            /** Status */
            status?: ("fed" | "partial" | "refused" | "skipped") | null;
            /** Qty */
            qty?: number | null;
            /** Food */
            food?: string | null;
            /** Food Size */
            food_size?: string | null;
            /** Poop */
            poop?: boolean | null;
            /** Weight */
            weight?: number | null;
            /** Note */
            note?: string | null;
        };
        /** EggLogCreate */
        EggLogCreate: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Egg Count */
            egg_count: number;
            /** Note */
            note?: string | null;
        };
        /** EggLogRead */
        EggLogRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Gecko Id
             * Format: uuid
             */
            gecko_id: string;
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Egg Count */
            egg_count: number;
            /** Note */
            note: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** EggLogUpdate */
        EggLogUpdate: {
            /** Date */
            date?: string | null;
            /** Egg Count */
            egg_count?: number | null;
            /** Note */
            note?: string | null;
        };
        /** EnvironmentLogCreate */
        EnvironmentLogCreate: {
            /**
             * Recorded At
             * Format: date-time
             */
            recorded_at?: string;
            /** Temperature */
            temperature: number;
            /** Humidity */
            humidity: number;
            /**
             * Source
             * @default manual
             * @enum {string}
             */
            source: "manual" | "sensor";
        };
        /** EnvironmentLogRead */
        EnvironmentLogRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Gecko Id
             * Format: uuid
             */
            gecko_id: string;
            /**
             * Recorded At
             * Format: date-time
             */
            recorded_at: string;
            /** Temperature */
            temperature: number;
            /** Humidity */
            humidity: number;
            /**
             * Source
             * @enum {string}
             */
            source: "manual" | "sensor";
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** EnvironmentLogUpdate */
        EnvironmentLogUpdate: {
            /** Recorded At */
            recorded_at?: string | null;
            /** Temperature */
            temperature?: number | null;
            /** Humidity */
            humidity?: number | null;
            /** Source */
            source?: ("manual" | "sensor") | null;
        };
        /** GeckoCreate */
        GeckoCreate: {
            /** Name */
            name: string;
            /** Morph */
            morph?: string | null;
            /**
             * Gender
             * @default unknown
             * @enum {string}
             */
            gender: "male" | "female" | "unknown";
            /** Birth Date */
            birth_date?: string | null;
            /** Acquired Date */
            acquired_date?: string | null;
            /**
             * Feeding Interval Days
             * @default 7
             */
            feeding_interval_days: number;
            /** Note */
            note?: string | null;
            /** Safe Temp Min */
            safe_temp_min?: number | null;
            /** Safe Temp Max */
            safe_temp_max?: number | null;
            /** Safe Humidity Min */
            safe_humidity_min?: number | null;
            /** Safe Humidity Max */
            safe_humidity_max?: number | null;
        };
        /** GeckoRead */
        GeckoRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Morph */
            morph: string | null;
            /**
             * Gender
             * @enum {string}
             */
            gender: "male" | "female" | "unknown";
            /** Birth Date */
            birth_date: string | null;
            /** Acquired Date */
            acquired_date: string | null;
            /** Photo Path */
            photo_path: string | null;
            /** Feeding Interval Days */
            feeding_interval_days: number;
            /** Note */
            note: string | null;
            /** Safe Temp Min */
            safe_temp_min: number | null;
            /** Safe Temp Max */
            safe_temp_max: number | null;
            /** Safe Humidity Min */
            safe_humidity_min: number | null;
            /** Safe Humidity Max */
            safe_humidity_max: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** GeckoUpdate */
        GeckoUpdate: {
            /** Name */
            name?: string | null;
            /** Morph */
            morph?: string | null;
            /** Gender */
            gender?: ("male" | "female" | "unknown") | null;
            /** Birth Date */
            birth_date?: string | null;
            /** Acquired Date */
            acquired_date?: string | null;
            /** Feeding Interval Days */
            feeding_interval_days?: number | null;
            /** Note */
            note?: string | null;
            /** Safe Temp Min */
            safe_temp_min?: number | null;
            /** Safe Temp Max */
            safe_temp_max?: number | null;
            /** Safe Humidity Min */
            safe_humidity_min?: number | null;
            /** Safe Humidity Max */
            safe_humidity_max?: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** SheddingLogCreate */
        SheddingLogCreate: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Note */
            note?: string | null;
        };
        /** SheddingLogRead */
        SheddingLogRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Gecko Id
             * Format: uuid
             */
            gecko_id: string;
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Note */
            note: string | null;
            /** Photos */
            photos: components["schemas"]["SheddingPhotoRead"][];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** SheddingLogUpdate */
        SheddingLogUpdate: {
            /** Date */
            date?: string | null;
            /** Note */
            note?: string | null;
        };
        /** SheddingPhotoRead */
        SheddingPhotoRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** File Path */
            file_path: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_geckos_geckos_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GeckoRead"][];
                };
            };
        };
    };
    create_gecko_geckos_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GeckoCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GeckoRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_gecko_geckos__gecko_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                gecko_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GeckoRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_gecko_geckos__gecko_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                gecko_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_gecko_geckos__gecko_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                gecko_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GeckoUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GeckoRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_gecko_photo_geckos__gecko_id__photo_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                gecko_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_gecko_photo_geckos__gecko_id__photo_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GeckoRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_daily_logs_geckos__gecko_id__daily_logs_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                gecko_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DailyLogRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_daily_log_geckos__gecko_id__daily_logs_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                gecko_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DailyLogCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DailyLogRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_daily_log_daily_logs__log_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                log_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DailyLogRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_daily_log_daily_logs__log_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                log_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_daily_log_daily_logs__log_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                log_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DailyLogUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DailyLogRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_shedding_logs_geckos__gecko_id__shedding_logs_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                gecko_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SheddingLogRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_shedding_log_geckos__gecko_id__shedding_logs_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                gecko_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SheddingLogCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SheddingLogRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_shedding_log_shedding_logs__log_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                log_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SheddingLogRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_shedding_log_shedding_logs__log_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                log_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_shedding_log_shedding_logs__log_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                log_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SheddingLogUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SheddingLogRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_shedding_photos_shedding_logs__log_id__photos_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                log_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_shedding_photos_shedding_logs__log_id__photos_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SheddingPhotoRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_shedding_photo_shedding_photos__photo_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                photo_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_environment_logs_geckos__gecko_id__environment_logs_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                gecko_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnvironmentLogRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_environment_log_geckos__gecko_id__environment_logs_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                gecko_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EnvironmentLogCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnvironmentLogRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_environment_log_environment_logs__log_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                log_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnvironmentLogRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_environment_log_environment_logs__log_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                log_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_environment_log_environment_logs__log_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                log_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EnvironmentLogUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnvironmentLogRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_egg_logs_geckos__gecko_id__egg_logs_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                gecko_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EggLogRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_egg_log_geckos__gecko_id__egg_logs_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                gecko_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EggLogCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EggLogRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_egg_log_egg_logs__log_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                log_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EggLogRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_egg_log_egg_logs__log_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                log_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_egg_log_egg_logs__log_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                log_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EggLogUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EggLogRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
